export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAILURE = "REGISTER_FAILURE";
export const LOGING_SUCCESS = "LOGING_SUCCESS";
export const LOGING_FAILURE = "LOGING_FAILURE";
export const CLEAR_AUTH_ERROR = "CLEAR_AUTH_ERROR";
export const CLEAR_REGISTER = "CLEAR_REGISTER";
