export const ADD_GROUP_SUCCESS = "ADD_GROUP_SUCCESS";
export const ADD_GROUP_FAILURE = "ADD_GROUP_FAILURE";
export const CLEAR_ERROR = "CLEAR_ERROR";
export const USER_ADDED_SUCCESS = "USER_ADDED_SUCCESS";
export const USER_ADDED_FAILURE = "USER_ADDED_FAILURE";
export const GET_ALL_GROUPS = "GET_ALL_GROUPS";
export const GET_ALL_USERS_OF_GROUP_SUCCESS = "GET_ALL_USERS_OF_GROUP_SUCCESS";
export const GET_ALL_USERS_OF_GROUP_FAILURE = "GET_ALL_USERS_OF_GROUP_FAILURE";
